Profile edit page
TechNullogy/Simple-Shop pull request #20
Opened 2023-06-15 12:48 UTC by tahmin1992

please check my profile-edit form

2023-07-23 13:33 UTC, AmirHosseinKarimi commented
![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTFjZjRlYmItMjg5Ny00YjMzLWFmNTEtYzAwZWFjNzE2YWMwIiwiZGVwbG95X2lkIjoiNjQ5NDc4OGUzMDU2MTgwMDA4ZjQyMTE2IiwiaWQiOiI2MDljNWI1Yi1hNjY0LTRkNDctYTg4OS04Y2M2YjRkYzZlYzkifQ==)

Fit fields width like as grid on design. 
<details><summary>Browser metadata</summary>





```
Path:      /src/pages/profile-edit.html
Browser:   Firefox 116.0 on Linux x86_64
Viewport:  2560 x 1283 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-20--simple-shop-technullogy.netlify.app%2Fsrc%2Fpages%2Fprofile-edit.html&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=116.0&resolution=2560x1283&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-20--simple-shop-technullogy.netlify.app/src/pages/profile-edit.html) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6494788e3056180008f42116&commentID=64bd2c2bc1e59423fd3b7447&resolution=resolved)

2023-07-23 13:41 UTC, AmirHosseinKarimi commented
Use `<input type="test" inputMode="numeric" />` for numeric inputs with numeric keyboard without increase/decrease buttons.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTFjZjRlYmItMjg5Ny00YjMzLWFmNTEtYzAwZWFjNzE2YWMwIiwiZGVwbG95X2lkIjoiNjQ5NDc4OGUzMDU2MTgwMDA4ZjQyMTE2IiwiaWQiOiIwMDRjODEzMC02ODExLTQ3ZGUtOGMwMi0wNGJmNjk4YjkwOWUifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /src/pages/profile-edit.html
Browser:   Firefox 116.0 on Linux x86_64
Viewport:  2560 x 1283 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-20--simple-shop-technullogy.netlify.app%2Fsrc%2Fpages%2Fprofile-edit.html&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=116.0&resolution=2560x1283&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-20--simple-shop-technullogy.netlify.app/src/pages/profile-edit.html) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6494788e3056180008f42116&commentID=64bd2e18b5c95225857632be&resolution=resolved)

2023-07-23 13:44 UTC, AmirHosseinKarimi commented
Its a [select](https://www.w3schools.com/tags/tag_select.asp) element like as drop-down. Not a text input.

![screenshot](https://netlify-cocoon.netlify.app/.netlify/functions/fetch?code=307&path=eyJzaXRlX2lkIjoiMTFjZjRlYmItMjg5Ny00YjMzLWFmNTEtYzAwZWFjNzE2YWMwIiwiZGVwbG95X2lkIjoiNjQ5NDc4OGUzMDU2MTgwMDA4ZjQyMTE2IiwiaWQiOiI3NTMyMzdmZS1hOTQ1LTQyODgtOTE5OS1jYTJkMjcyNjdkMWQifQ==)


<details><summary>Browser metadata</summary>





```
Path:      /src/pages/profile-edit.html
Browser:   Firefox 116.0 on Linux x86_64
Viewport:  2560 x 1283 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-20--simple-shop-technullogy.netlify.app%2Fsrc%2Fpages%2Fprofile-edit.html&os=OS%20X&os_version=Big%20Sur&browser=Firefox&browser_version=116.0&resolution=2560x1283&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-20--simple-shop-technullogy.netlify.app/src/pages/profile-edit.html) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6494788e3056180008f42116&commentID=64bd2ea2efc13a25528a5c33&resolution=resolved)

2023-07-23 13:58 UTC, AmirHosseinKarimi requested changes

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +          <input type="text" class="w-[230px] h-[50px] bg-[#F7F9FC] text-right mr-5 pr-3" value="علیض">
```suggestion
          <input type="text" class="w-[230px] h-[50px] bg-[#F7F9FC] text-right mr-5 pr-3" value="" placeholder="علیرضا">
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +          <input type="text" class="w-[230px] h-[50px] bg-[#F7F9FC] text-right mr-5 pr-3" value="علیض">
Clear all field values & add an example value as a placeholder.

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +      <h2 class="w-[249px] h-[36px]  not-italic font-bold text-[20px] leading-[36px] m-5">ویرایش اطلاعات شخصی</h2>
Remove all fixed widths & heights. Elements should have dynamic size. Instead, use `line-height` to set the element's inner height.

```suggestion
      <h2 class="not-italic font-bold text-[20px] leading-[36px] m-5">ویرایش اطلاعات شخصی</h2>
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +    <form class="flex flex-col gap-3  bg-[#FFFFFF] h-[528px] w-[986px] ">
Use TailwindCSS classes.

```suggestion
    <form class="flex flex-col gap-3  bg-white h-[528px] w-[986px] ">
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +          <label class="w-[88px] h-[17px]  not-italic font-light text-[12px] leading-[16 .8px] text-[#7E8AAB] mt-5">شماره موبایل</label>
Remove all `not-italic` classes. It is useless.

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +          <label class="w-[88px] h-[17px]  not-italic font-light text-[12px] leading-[16 .8px] text-[#7E8AAB] mt-5 mr-5">استان</label>
Use TailwindCSS classes.

```suggestion
          <label class="w-[88px] h-[17px]  not-italic font-light text-xs text-[#7E8AAB] mt-5 mr-5">استان</label>
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on tailwind.config.js
> +    },
Useless change...
Prevent any useless changes & config your IDE according to project settings.

```suggestion
    extend: {},
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +              <img class="  absolute top-12 right-10" src="/src/assets/images/pages/ui/profile-circle.png"   alt="profile-image">
Remove any unnecessary spaces between attributes & values.
Use Prettier formater

```suggestion
              <img class="absolute top-12 right-10" src="/src/assets/images/pages/ui/profile-circle.png" alt="profile-image">
```

2023-07-23 13:58 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +          <label class="w-[88px] h-[17px]  not-italic font-light text-[12px] leading-[16 .8px] text-[#7E8AAB] mt-5">شهر</label>
Use the nearest TailwindCSS classes if there is a small difference.

2023-08-21 19:15 UTC, tahminehrivandi commented
I edit my profile edit page please check it_

2023-08-25 17:26 UTC, AmirHosseinKarimi commented on tailwind.config.js
> +        'gray': '#7a7f8d',
TailwindCSS has these colors by default. If you need to add any other color define them with a different name.
Use [this tool](https://chir.ag/projects/name-that-color) to name colors.

2023-08-25 17:26 UTC, AmirHosseinKarimi commented on src/pages/profile-edit.html
> +      <div class="m-10 flex flex-col gap-y-6 rounded p-3" dir="rtl">
Change the page direction instead of elements.

2023-08-25 17:33 UTC, AmirHosseinKarimi commented
Hi Tahmineh. I hope you are doing well.
First of all. Good job :clap: I can see your progress and am happy for you. Keep going girl.

I refactored the code and applied some changes in a [new branch](https://github.com/TechNullogy/Simple-Shop/tree/profile-edit-page).
You can pull this branch like as main branch and create a new pull request to merge with the main branch.
Feel free to apply any changes to the code.

2023-08-25 17:33 UTC, closed without merging